### ISSUE TITLE
Use pages.github.com hosting

### ISSUE THREAD

**Issue by davelab6** [AmeliaBR/accessible-graphics-notes#1]
Please branch to the gh-pages branch so that the page is accessible online:

``` sh
git checkout -b gh-pages;
git push origin gh-pages;
```

Then go to https://github.com/AmeliaBR/accessible-graphics-notes/settings and set `gh-pages` as the default branch, then delete `master`:

``` sh
git branch -D master;
git push origin :master
```

**Comment by davelab6** [comment]
(Or you could just add a README with a link to https://rawgit.com/AmeliaBR/accessible-graphics-notes/master/ABR-AccessibleGraphics-LGM2015.html :)

**Comment by AmeliaBR** [comment]
For some reason I was under the impression that Github Pages were restricted to paid Github accounts (which is why I was using rawgit), but now I can't find any such reference.

Leaving the issue open so I remember to (eventually) follow up and implement the standard solution.

**Comment by davelab6** [comment]
:+1:
